on: [release]
name: Golang Build and Upload Release Asset
jobs:
  build:
    name: Build and Release
    strategy:
      matrix:
        go_os: [linux, darwin, windows]
        go_arch: [amd64]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Build
      env:
        GOARCH: ${{ matrix.go_arch }}
        GOOS: ${{ matrix.go_os }}
        RELEASE: ${{ github.event.release.tag_name }}
        BUILDNUMBER: ${{ github.event.release.tag_name }}
      run: make build
    - name: Pack binary (windows)
      if: matrix.go_os == 'windows'
      run: |
          mv bin/awsic bin/awsic.exe
          zip awsic.zip bin/*
    - name: Pack binary
      if: matrix.go_os != 'windows'
      run: zip awsic.zip bin/*
    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          mv awsic.zip awsic-${{ matrix.go_arch }}-${{ matrix.go_os }}-${{github.event.release.tag_name}}.zip
          gh release upload ${{ github.event.release.upload_url }} awsic-${{ matrix.go_arch }}-${{ matrix.go_os }}-${{github.event.release.tag_name}}.zip
